import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import React from 'react'
import ReactDOM from 'react-dom/client'
import { PersistGate } from 'redux-persist/integration/react'
import { BrowserRouter } from 'react-router-dom'
import { store, persistor } from '../redux/store'
import 'modern-normalize';
import { ReduxProvider } from "@/redux/features/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dana Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><ReduxProvider>
        <>{children}</>
      </ReduxProvider></body>
    </html>
  );
}
